version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8002"
    depends_on:
      - "mongo"
    volumes:
      - .:/app/code


  mongo:
    image: "ehazlett/mongodb"
    environment:
      - DATA_DIR=/data/db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
